// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwugnlhmwwynykdokevx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13dWdubGhtd3d5bnlrZG9rZXZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NjQ1NzMsImV4cCI6MjA2NzU0MDU3M30.d71otyQ8_DC9j7s8JOWXoxXrQMn2gpFYv4mrROkRS0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});